version: "3.9"

services:
  # 1. MySQL 데이터베이스 (창고) 설정 - 이 부분은 그대로 사용합니다.
  mysql:
    image: mysql:8.4
    container_name: sijang-mission
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: sijang1
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "1234"
      TZ: "Asia/Seoul"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "user", "-p1234"]
      interval: 5s
      timeout: 3s
      retries: 20

  # 2. 백엔드 애플리케이션 (주방) 설정 - 이 부분이 추가되었습니다.
  backend:
    build: .  # ← 현재 폴더의 Dockerfile을 사용하여 이미지를 자동으로 빌드하라는 뜻입니다.
    container_name: backend-app
    restart: always
    ports:
      - "8080:8080" # ← 내 컴퓨터의 8080과 컨테이너의 8080을 연결
    environment:
      - SPRING_PROFILES_ACTIVE=docker # ← application.yml의 docker 프로필을 활성화
    depends_on:
      mysql:
        condition: service_healthy # ← mysql 컨테이너가 완전히 준비되면 backend를 시작

volumes:
  mysql_data:
    driver: local